# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'RxSwift-BriefingPaper-Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-BriefingPaper-Sample
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'RxSwift-BriefingPaper-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-BriefingPaper-SampleUITests' do
    # Pods for testing
  end

end
